### PR TITLE
remove file url_expiration

### PR DESCRIPTION
**Pull request by Schparky**
We decided a while back that URL expiration isn't necessary. 

Also did a bit of refactoring, which is why so many files were touched.

### CODE REVIEW

**Review by Baggerone — APPROVED** [review]
Wow. Lots of work.

**Comment by Schparky** [comment]
> Wow. Lots of work.

Nah, just a bunch of copy-paste. If `CreateFileFixture` had existed prior to this, only a few files would have been touched.

**Comment by Schparky** [comment]
> Wow. Lots of work.

Nah, just a bunch of copy-paste. If `CreateFileFixture` had existed prior to this, only a few files would have been touched.

**Comment by Schparky** [comment]
After further thought, we probably want to keep the expiration

**Pull request closed without merging**
